Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

================== RESTART: D:/Desktop/rock-paper-scissors.py ==================
Water, Fire, Air. How it works: Water beats Fire, Fire beats Air, and Air beats Water
0 Wins, 0 Losses, 0 Ties
Enter your move: (W)ater (F)ire (A)ir or (Q)uit
> W
WATER versus...
1...
2...
3...
FIRE
You win!
1 Wins, 0 Losses, 0 Ties
Enter your move: (W)ater (F)ire (A)ir or (Q)uit
> F
FIRE versus...
1...
2...
3...
WATER
You lose!
1 Wins, 1 Losses, 0 Ties
Enter your move: (W)ater (F)ire (A)ir or (Q)uit
> A
AIR versus...
1...
2...
3...
WATER
You win!
2 Wins, 1 Losses, 0 Ties
Enter your move: (W)ater (F)ire (A)ir or (Q)uit
> A
AIR versus...
1...
2...
3...
WATER
You win!
3 Wins, 1 Losses, 0 Ties
Enter your move: (W)ater (F)ire (A)ir or (Q)uit
> W
WATER versus...
1...
2...
3...
WATER
It is a tie!
3 Wins, 1 Losses, 1 Ties
Enter your move: (W)ater (F)ire (A)ir or (Q)uit
> 